on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - "linux/amd64"
          - "linux/arm64"
          - "linux/ppc64le"
          - "linux/s390x"
          - "linux/arm/v7"
          - "linux/arm/v6"

    name: Linux, architecture ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Build Image
        run: |
          cd DockerBuild/Build
          arch="${{ matrix.arch }}" node build.js

      - name: copy files
        run: |
          IMSHA="$(docker manifest inspect -v dockerruns | jq -r '.[0].Descriptor.digest')"
          echo "docker run -v $(pwd)/:/home/OUT/ dockerruns@${IMSHA}"
          echo "docker run -v $(pwd)/:/home/OUT/ dockerruns@${IMSHA}" | bash -

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: DockerRunBuild_*
          prerelease: true
          body: Linux, architecture ${{ matrix.arch }}

  win32:
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: copy files
        run: npm run bin

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: DockerRunBuild_*
          prerelease: true
          body: Windows X64

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: copy files
        run: npm run bin

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: DockerRunBuild_*
          prerelease: true
          body: MacOS X64